// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      acceptAlert: function () {
        http.post('/accept_alert');
      },
      dismissAlert: function () {
        http.post('/dismiss_alert');
      },
      getAlertText: function () {
        var response;
        response = http.get('/alert_text');
        return parseResponseData(response);
      },
      typeAlert: function (text) {
        http.post('/alert_text', { text: text });
      }
    };
  };
}.call(this);
