// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      setLocalStorageKey: function (key, value) {
        http.post('/local_storage', {
          key: key,
          value: value
        });
      },
      getLocalStorageKeys: function () {
        var response;
        response = http.get('/local_storage');
        return parseResponseData(response);
      },
      clearLocalStorage: function () {
        http['delete']('/local_storage');
      }
    };
  };
}.call(this);
