// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      getGeolocation: function () {
        var response;
        response = http.get('/location');
        return parseResponseData(response);
      },
      setGeolocation: function (location) {
        http.post('/location', { location: location });
      }
    };
  };
}.call(this);
