// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      moveTo: function (elementId) {
        return http.post('/moveto', {
          element: elementId,
          xoffset: null,
          yoffset: null
        });
      }
    };
  };
}.call(this);
