// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      navigateTo: function (url) {
        http.post('/url', { url: url });
      },
      refresh: function () {
        http.post('/refresh');
      },
      getUrl: function () {
        var response;
        response = http.get('/url');
        return parseResponseData(response);
      }
    };
  };
}.call(this);
