// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      getPageTitle: function () {
        var response;
        response = http.get('/title');
        return parseResponseData(response);
      },
      getPageSource: function () {
        var response;
        response = http.get('/source');
        return parseResponseData(response);
      },
      getScreenshot: function () {
        var response;
        response = http.get('/screenshot');
        return parseResponseData(response);
      },
      setPageSize: function (param$) {
        var cache$, height, width;
        {
          cache$ = param$;
          height = cache$.height;
          width = cache$.width;
        }
        http.post('/window/current/size', {
          height: height,
          width: width
        });
      },
      getPageSize: function () {
        var response;
        response = http.get('/window/current/size');
        return parseResponseData(response);
      }
    };
  };
}.call(this);
