// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var cleanResponse, json, validateResponse;
  json = require('./json');
  cleanResponse = function (response) {
    delete response.screen;
    delete response.hCode;
    return delete response['class'];
  };
  validateResponse = function (response) {
    var friendlyError;
    if (!(null != response.message) || !(null != response.stackTrace))
      return;
    friendlyError = new Error(response.message);
    friendlyError.inner = response;
    throw friendlyError;
  };
  module.exports = function (response) {
    var data;
    if (response.body === '')
      return null;
    data = response.body.toString();
    response = json.tryParse(data).value;
    if (null != response) {
      cleanResponse(response);
      validateResponse(response);
    }
    return response;
  };
}.call(this);
