// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var assert, json, parseResponseData;
  assert = require('assertive');
  json = require('./json');
  parseResponseData = require('./parse_response');
  module.exports = function (request, serverUrl, desiredCapabilities) {
    var capabilities, data, response, sessionId, url;
    url = '' + serverUrl + '/session';
    data = JSON.stringify({ desiredCapabilities: desiredCapabilities });
    response = request(url, 'POST', data);
    assert.equal('Failed to start Selenium session. Check the selenium.log.', response.statusCode, 200);
    sessionId = json.tryParse(response.body.toString()).sessionId;
    capabilities = parseResponseData(response);
    assert.truthy('found sessionId', sessionId);
    return {
      sessionId: sessionId,
      capabilities: capabilities
    };
  };
}.call(this);
