// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var parseResponseData;
  parseResponseData = require('./parse_response');
  module.exports = function (http) {
    return {
      switchToDefaultFrame: function () {
        http.post('/frame');
      },
      switchToFrame: function (indexOrNameOrId) {
        http.post('/frame', { id: indexOrNameOrId });
      },
      getCurrentWindowHandle: function () {
        var response;
        response = http.get('/window_handle');
        return parseResponseData(response);
      },
      switchToWindow: function (name) {
        http.post('/window', { name: name });
      },
      closeWindow: function () {
        http['delete']('/window');
      }
    };
  };
}.call(this);
